development:
  :address: smtp.postmark.com
  :port: 587
  :authentication: plain
  :user_name: d14821d9-a5ec-4176-b658-5232ea0a7467
  :password: d14821d9-a5ec-4176-b658-5232ea0a7467
  :enable_starttls_auto: true
production:
  :address: smtp.postmark.com
  :port: 587
  :authentication: plain
  :user_name: d14821d9-a5ec-4176-b658-5232ea0a7467
  :password: d14821d9-a5ec-4176-b658-5232ea0a7467
  :enable_starttls_auto: true