development:
  :address: smtp.postmark.com
  :port: 587
  :authentication: plain
  :user_name: 2642ab79-52e1-438b-a5b7-46c340e70ed1
  :password: 2642ab79-52e1-438b-a5b7-46c340e70ed1
  :enable_starttls_auto: true
production:
  :address: smtp.postmark.com
  :port: 587
  :authentication: plain
  :user_name: 2642ab79-52e1-438b-a5b7-46c340e70ed1
  :password: 2642ab79-52e1-438b-a5b7-46c340e70ed1
  :enable_starttls_auto: true