# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Subject.create(name: "Chem 167")
# Subject.create(name: "Chem 177")
# Subject.create(name: "Chem 201")
# Subject.create(name: "Chem 211")
# Subject.create(name: "Chem 231")
# Subject.create(name: "Chem 178")
# Subject.create(name: "Chem 163")
# Subject.create(name: "Chem 50")
# Subject.create(name: "Chem 316")
# Subject.create(name: "Chem 325")
# Subject.create(name: "Chem 331")
# Subject.create(name: "Chem 332")
# Subject.create(name: "Chem 402")
# Subject.create(name: "Chem 502")
# Subject.create(name: "Phys 101")
Subject.create(name: "Phys 221")
# Subject.create(name: "Phys 222")
# Subject.create(name: "Phys 50")
# Subject.create(name: "Phys 111")
# Subject.create(name: "Phys 112")
# Subject.create(name: "Phys 115")
# Subject.create(name: "Phys 198")
# Subject.create(name: "Phys 199")
# Subject.create(name: "Phys 241")
# Subject.create(name: "Phys 298")
# Subject.create(name: "Phys 304")
# Subject.create(name: "Phys 321")
# Subject.create(name: "Phys 362")
# Subject.create(name: "Phys 364")
# Subject.create(name: "Phys 421")
# Subject.create(name: "Phys 461")
# Subject.create(name: "Phys 480")
# Subject.create(name: "Math 10")
# Subject.create(name: "Math 104")
# Subject.create(name: "Math 140")
# Subject.create(name: "Math 143")
# Subject.create(name: "Math 145")
# Subject.create(name: "Math 150")
# Subject.create(name: "Math 151")
Subject.create(name: "Math 160")
# Subject.create(name: "Math 165")
# Subject.create(name: "Math 166")
# Subject.create(name: "Math 181")
# Subject.create(name: "Math 195")
# Subject.create(name: "Math 196")
# Subject.create(name: "Math 201")
# Subject.create(name: "Math 265")
# Subject.create(name: "Math 266")
# Subject.create(name: "Math 267")
# Subject.create(name: "Math 268")
# Subject.create(name: "Math 269")
# Subject.create(name: "Math 297")
# Subject.create(name: "Math 301")
# Subject.create(name: "Math 304")
# Subject.create(name: "Math 317")
# Subject.create(name: "Math 331")
# Subject.create(name: "Math 341")
# Subject.create(name: "Math 342")
